language: python

python: 
  - "2.7"
  - "3.5"

install: 
  - "pip install pytest-cov"

script: 
  - "py.test --dataDir=./test/data1 --cov=keboola --cov-report term-missing"

notifications: 
  slack: "keboola:fym2t4112jahUATYBYFS3oBS"
