language: python

python:
  - 3.5

install:
  - python setup.py install
  - pip install flake8

script:
  - flake8
  - python test/test_docker.py

notifications:
  slack: keboola:NCe8LwHlAyQBD4KS8BM0JkuA