language: python

python:
  - 3.5

install:
  - python setup.py install
  - pip install flake8

script:
  - flake8
  - python test/test_docker.py

notifications:
  email: false
  slack:
    secure: xqI2VxhlQAlUqM+NscRbsuHAh/kUjWXqNGLB3YZHGAQRCaSxQx6mSwVlJJagPC3jd/LOYuOVZpmpjKzpzYlA+8zFxTjqRqeZDk2PyaN5wCyZz+LR4V3f6E5MNlxad9RHF6EsQfr8QCma6Zhj71rGoVT047/aXb1mvIRHXAuqSGGHxwdwJhlR5UWdbTI7BMhpPShq/YDDVVVAG/t4+GevTQxxmZ00MgcKOOE53sN4O8ioI+DgtHuQmdvYEWd3MEtM/CFx1BpRf7vMKPl71ER9J1B7WmS4BykMRH9pD3vmTbGmJRZPje7pXJug3HtKVFF5JkzMOYn002ej8GntWYOC4CPsleD5gBZVxFYxSPIRWQJpMrWup5ZH2tVoTwZLj8Z22PSeRBoNlflGqVnloaD8t5cDV+ig/XhrGFgdnEr0ZdPwROzGQIV9rfVLXYZ/1iNwwK+WwG63sF+YkCVBiYR15TQikUnZI8JEu6cjsAwBtDuTuGMaHTbLo/wPv739adC/anNza/26bB0yVtfS5XgUfgQyhjEcfTt+eegbDGuJ5qxT/mdG6kxbO5lhLHTYMhwShrk44psTSj5ijTBaah+xJkWGTtQoC4gfFwjUFechaNcRKy22fwp2RBFtAJZiRHCrkDEmZo5Iy+SpKWmNT/MYKNGKJEJbP5qL7Zh+aCH4t/k=
